title: praxis
email: praxis.nyc@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Decolonize your attention
baseurl: ''
url: 'https://praxis.nyc/'
twitter_username: nonlinear
github_username: nonlinear

sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
